### PR TITLE
basic TypeScript support

### PR DESCRIPTION
**Pull request by lifeart**
ref https://github.com/emberwatch/ember-language-server/issues/81

### CODE REVIEW

**Comment by lifeart** [comment]
@chriskrycho can you check my implementation?

**Comment by lifeart** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30109/files crosslink

**Comment by chriskrycho** [comment]
Just saw this as you got it working; sorry for never getting back to you, @lifeart! (October was a really, real,y rough month for me personally so a lot of things got missed then.)

**Comment by lifeart** [comment]
@chriskrycho np, main blocking point is "Out of the box ts parsing", 

issue with test in - https://github.com/lifeart/ember-meta-explorer/pull/3 If you have time to get it working - it will be great!

**Pull request closed without merging**
