### PR TITLE
Components & helpers completion

### PR DESCRIPTION
**Pull request by t-sauer**
autocomplete

### CODE REVIEW

**Comment by Turbo87** [comment]
let's try this... bors r+

**Comment by Turbo87** [comment]
@locks I don't understand how this is supposed to work :-/

**Comment by locks** [comment]
I think it needs to be on a line by itself?

**Comment by notriddle** [comment]
Nope, it's three things I can think of that delay a PR review:

1. I'm running on Heroku free tier right now, so bors gets slept.
2. Bors deliberately waits a few seconds, in case multiple PRs get reviewed in quick succession and it can batch them together.
3. It does take time for GitHub to deliver webhooks. The other two are bigger factors, though.

**Comment by Turbo87** [comment]
@notriddle I guess I expected a message from bors (like @homu does) that acks my r+ even if it doesn't merge/test directly

**Comment by notriddle** [comment]
It's on the planning radar. Just working on a better test harness right now before doing further feature work.

**Pull request merged**
